
DATA:
  DATASET: "waterbirds"
  BATCH_SIZE: 96
  NUM_CLASSES: 2

  # Bias level, between [0, 1.0]. Make sure this is consistent with the actual dataset being used.
  CONFOUNDING_FACTOR: 1.0

  # Directory under ./data holding dataset
  WATERBIRDS_DIR: "waterbird_1.0_forest2water2"

  ATTENTION_DIR: "clip_rn50_attention_gradcam"

EXP:
  APPROACH: "generic"

  MODEL: "resnet50"
  PRETRAINED: True

  LOSSES:
    CLASSIFICATION:
      WEIGHT: 1
    GRADIENT_OUTSIDE:
      COMPUTE: True
      LOG: False
      WEIGHT: 10000
      CRITERION: "L1"
      GT: "clip_rn50"
      COMBINE_ATT_MODE: "average_nonzero"

  NUM_EPOCHS: 200
  OPTIMIZER: "SGD"
  WEIGHT_DECAY: 1e-5
  MOMENTUM: 0.9

  SCHEDULER: "NONE"

  # Backbone of model
  BASE:
    LR: 0.005

  # Classifier portion of model
  CLASSIFIER:
    LR: 0.0001

