DATA:
  DATASET: "waterbirds"
  ROOT: "./data"

  CONFOUNDING_FACTOR: 0.95
  WATERBIRDS_DIR: "waterbird_complete95_forest2water2"
  REMOVE_BACKGROUND: False

  ATTENTION_DIR: "NONE" # Since attention will be created
  SIZE: 224

APPROACH: "clip"

SAVE_FOLDER: "clip_rn50_attention_gradcam"
MODEL_TYPE: "RN50"
ATTENTION_TYPE: "gradcam"
TARGET_LAYER: "layer4.2.relu"

#SAVE_FOLDER: "clip_vit_attention"
#MODEL_TYPE: "ViT-B/32"
#ATTENTION_TYPE: "transformer"

# Prompt settings:
# - If USE_PROMPTS_PER_CLASS is True, attention for each image
#   depends on its class label. In this case, PROMPTS_PER_CLASS
#   should contain a list of length # classes, with entry i holding
#   the prompts for class i.
# - Otherwise, if USE_PROMPTS_PER_CLASS is False, then every image
#   gets the same prompts, which are specified in PROMPTS.
USE_PROMPTS_PER_CLASS: False
PROMPTS_PER_CLASS:
  - ["an image of a landbird", "a photo of a landbird"]
  - ["an image of a waterbird", "a photo of a waterbird"]


# General prompts, used if USE_PROMPTS_PER_CLASS is False
PROMPTS: ["an image of a bird", "a photo of a bird"]



